# Generated by Django 5.0.1 on 2024-01-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('height', models.FloatField()),
                ('birth_date', models.DateField()),
                ('wake_up_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_student', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
