# Generated by Django 4.2.4 on 2023-10-28 18:37

from django.db import migrations


def age_group_updater(apps, schema_editor):
    persons_model = apps.get_model("main_app", "Person")
    persons = persons_model.objects_all()

    for person in persons:
        if person.age <= 12:
            


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0009_person"),
    ]

    operations = []
